### ISSUE TITLE
diet_data.zip file is corrupt!

### ISSUE THREAD

**Issue by IbrahimIbrahim** [derekfranks/practice_assignment#4]
it does not open nor extract its contents from github!
I used  http://s3.amazonaws.com/practice_assignment/diet_data.zip instead.

**Comment by derekfranks** [comment]
Try downloading it again.  I just checked it and it opens and extracts correctly.

**Comment by IbrahimIbrahim** [comment]
nope! It really doesn't Derek! the OS on your side probably uploaded it into memory from your browser cache rather than downloading the "corrupt" file from Github.

**Comment by derekfranks** [comment]
I went ahead and deleted it.  I'd rather people download it from the amazon link anyways.
